### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by AiVerisimilitude**
These are some minor fixes to have it running on the latest version of ros-humble

### CODE REVIEW

**Comment by fateshelled** [comment]
Thanks for your pull request. 
`cv_bridge.hpp` does not seem to exist. what version of ROS 2 Humble did you use?

**Comment by AiVerisimilitude** [comment]
You're totally right, sorry. This is for rolling, which I guess will soon be in jazzy. I got the package manually since I wanted the type-adaptation, which they only released for rolling so far.

Here is the link to their GitHub:
https://github.com/ros-perception/vision_opencv/tree/rolling/cv_bridge/include/cv_bridge

**Comment by fateshelled** [comment]
Could you please fix include header? Or is it possible to switch the header file depending on the ROS version?

**Comment by AiVerisimilitude** [comment]
I was thinking what was the best approach and I think this is the best. I forward the version of cv_bridge as preprocessor macros, so I can then check if it's a newer version of the package and if so, include the correct header.

It's a bit ugly, so if you want I can move it to a separate header where this is checked. What do you think?

**Comment by fateshelled** [comment]
Thanks for the fix!
It looks like it would be better to branch with cv_bridge version rather than with ROS_DISTRO. 
If there are no problems with build, I'll merge this code as is.

**Pull request merged**
